{{- if not .Values.externalDatabase.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hikma-health.fullname" . }}-db
  labels:
    {{- include "hikma-health.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "hikma-health.databaseUrl" . | quote }}
{{- end }}
